import About from '@/components/About';
import ContactMe from '@/components/ContactMe';
import Experiences from '@/components/Experiences';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Projects from '@/components/Projects';
import Skills from '@/components/Skills';
import Head from 'next/head';
import Link from 'next/link';
import { ArrowUpCircleIcon } from '@heroicons/react/24/outline';
import { GetStaticProps } from 'next';
import { Experience, PageInfo, Project, Skill, Social } from '@/typings';
import { fetchPageInfo } from '@/utils/fetchPageInfo';
import { fetchExperiences } from '@/utils/fetchExperiences';
import { fetchSkills } from '@/utils/fetchSkills';
import { fetchSocials } from '@/utils/fetchSocials';
import { fetchProjects } from '@/utils/fetchProjects';

type Props = {
    pageInfo: PageInfo;
    experiences: Experience[];
    skills: Skill[];
    socials: Social[];
    projects: Project[];
};

export default function Home({
    pageInfo,
    experiences,
    skills,
    socials,
    projects,
}: Props) {
    return (
        <div
            className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scroll-smooth
         scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80"
        >
            <Head>
                <title>{`Hi, I'm Rahul`}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header socials={socials} />

            <section id="hero" className="snap-start">
                <Hero pageInfo={pageInfo} />
            </section>

            <section id="about" className="snap-center">
                <About pageInfo={pageInfo} />
            </section>

            <section id="experience" className="snap-center">
                <Experiences experiences={experiences} />
            </section>

            <section id="skills" className="snap-start">
                <Skills skills={skills} />
            </section>

            <section id="projects" className="snap-start">
                <Projects projects={projects} />
            </section>

            <section id="contact" className="snap-center">
                <ContactMe pageInfo={pageInfo} />
            </section>

            <Link href="#hero">
                <footer className="sticky z-500 bottom-4 w-full cursor-pointer">
                    <div className="flex items-center justify-center">
                        <ArrowUpCircleIcon className="h-8 w-8 text-[#F7AB0A]/50 animate-bounce" />
                    </div>
                </footer>
            </Link>
        </div>
    );
}

//we are writing this(middleware) code to perform client-side rendering in Next.js for static page generation
export const getStaticProps: GetStaticProps<Props> = async () => {
    const pageInfo: PageInfo = await fetchPageInfo();
    const experiences: Experience[] = await fetchExperiences();
    const skills: Skill[] = await fetchSkills();
    const socials: Social[] = await fetchSocials();
    const projects: Project[] = await fetchProjects();

    return {
        props: {
            pageInfo,
            experiences,
            skills,
            socials,
            projects,
        },
        //Next.js will attempt to re-generate the page:
        // when a comes in
        // At most once every 10 seconds
        revalidate: 10,
    };
};
